services:
  test:
    build:
      context: .
      dockerfile: Dockerfile.test
    networks:
      - servers
    depends_on:
      - server1
      - server2
      - server3
      - balancer

   balancer:
    command: ["lb", "--trace=true"]
    build: .
    networks:
      - servers
    container_name: lb  # <-- Додаємо ім’я контейнера

  server1:
    build: .
    networks:
      - servers

  server2:
    build: .
    networks:
      - servers

  server3:
    build: .
    networks:
      - servers

networks:
  servers: