name: Run Integration Tests

on:
  push:
  pull_request:

jobs:
  integration-tests:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker
      uses: docker/setup-buildx-action@v2
      
    - name: Check Docker Compose version
      run: docker compose version
      
    - name: Build and run integration tests
      run: docker-compose -f docker-compose.test.yaml up --abort-on-container-exit --build

    - name: Show logs on failure
      if: failure()
      run: docker compose -f docker-compose.test.yaml logs
